# Generated by Django 3.2.12 on 2023-03-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precipitationlong',
            name='location',
        ),
        migrations.RemoveField(
            model_name='temperaturelong',
            name='location',
        ),
        migrations.RemoveField(
            model_name='weatherwide',
            name='location',
        ),
        migrations.RemoveField(
            model_name='windlong',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='PrecipitationLong',
        ),
        migrations.DeleteModel(
            name='TemperatureLong',
        ),
        migrations.DeleteModel(
            name='WeatherWide',
        ),
        migrations.DeleteModel(
            name='WindLong',
        ),
    ]
